import { ICard } from './card.interface';

export const cards: [...ICard[][]] = [
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'img/cry.jpg',
      audioSrc: 'audio/cry.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'img/dance.jpg',
      audioSrc: 'audio/dance.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'img/dive.jpg',
      audioSrc: 'audio/dive.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'img/draw.jpg',
      audioSrc: 'audio/draw.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'img/fish.jpg',
      audioSrc: 'audio/fish.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'img/fly.jpg',
      audioSrc: 'audio/fly.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'img/hug.jpg',
      audioSrc: 'audio/hug.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'img/jump.jpg',
      audioSrc: 'audio/jump.mp3',
      categoryId: 1,
      categoryName: 'Action (set A)',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: 'img/open.jpg',
      audioSrc: 'audio/open.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'img/play.jpg',
      audioSrc: 'audio/play.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'img/point.jpg',
      audioSrc: 'audio/point.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'img/ride.jpg',
      audioSrc: 'audio/ride.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'img/run.jpg',
      audioSrc: 'audio/run.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'img/sing.jpg',
      audioSrc: 'audio/sing.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'img/skip.jpg',
      audioSrc: 'audio/skip.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'img/swim.jpg',
      audioSrc: 'audio/swim.mp3',
      categoryId: 2,
      categoryName: 'Action (set B)',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: 'img/cat.jpg',
      audioSrc: 'audio/cat.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'img/chick.jpg',
      audioSrc: 'audio/chick.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'img/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'img/dog.jpg',
      audioSrc: 'audio/dog.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'img/horse.jpg',
      audioSrc: 'audio/horse.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'img/pig.jpg',
      audioSrc: 'audio/pig.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'img/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'img/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
      categoryId: 3,
      categoryName: 'Animal (set A)',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'img/bird.jpg',
      audioSrc: 'audio/bird.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'img/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'img/frog.jpg',
      audioSrc: 'audio/frog.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'img/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'img/lion.jpg',
      audioSrc: 'audio/lion.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'img/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'img/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'img/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
      categoryId: 4,
      categoryName: 'Animal (set B)',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'img/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'img/pants.jpg',
      audioSrc: 'audio/pants.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'img/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'img/dress.jpg',
      audioSrc: 'audio/dress.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'img/boot.jpg',
      audioSrc: 'audio/boot.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'img/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'img/coat.jpg',
      audioSrc: 'audio/coat.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'img/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
      categoryId: 5,
      categoryName: 'Clothes',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'img/sad.jpg',
      audioSrc: 'audio/sad.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'img/angry.jpg',
      audioSrc: 'audio/angry.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'img/happy.jpg',
      audioSrc: 'audio/happy.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'img/tired.jpg',
      audioSrc: 'audio/tired.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'img/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'img/scared.jpg',
      audioSrc: 'audio/scared.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'img/smile.jpg',
      audioSrc: 'audio/smile.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'img/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
      categoryId: 6,
      categoryName: 'Emotions',
    },
  ],
  [
    {
      word: 'beet',
      translation: 'свёкла',
      image: 'img/beet.jpg',
      audioSrc: 'audio/beet.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'cabbage',
      translation: 'капуста',
      image: 'img/cabbage.jpg',
      audioSrc: 'audio/cabbage.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'carrot',
      translation: 'морковь',
      image: 'img/carrot.jpg',
      audioSrc: 'audio/carrot.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'cucumber',
      translation: 'огурец',
      image: 'img/cucumber.jpg',
      audioSrc: 'audio/cucumber.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'onion',
      translation: 'лук',
      image: 'img/onion.jpg',
      audioSrc: 'audio/onion.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'pepper',
      translation: 'перец',
      image: 'img/pepper.jpg',
      audioSrc: 'audio/pepper.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'potatoes',
      translation: 'картофель',
      image: 'img/potatoes.jpg',
      audioSrc: 'audio/potatoes.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
    {
      word: 'tomato',
      translation: 'помидор',
      image: 'img/tomato.jpg',
      audioSrc: 'audio/tomato.mp3',
      categoryId: 7,
      categoryName: 'Vegetables',
    },
  ],
  [
    {
      word: 'apple',
      translation: 'яблоко',
      image: 'img/apple.jpg',
      audioSrc: 'audio/apple.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: 'img/banana.jpg',
      audioSrc: 'audio/banana.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'grapes',
      translation: 'виноград',
      image: 'img/grapes.jpg',
      audioSrc: 'audio/grapes.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'lemon',
      translation: 'лимон',
      image: 'img/lemon.jpg',
      audioSrc: 'audio/lemon.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'melon',
      translation: 'дыня',
      image: 'img/melon.jpg',
      audioSrc: 'audio/melon.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'orange',
      translation: 'апельсин',
      image: 'img/orange.jpg',
      audioSrc: 'audio/orange.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'peach',
      translation: 'персик',
      image: 'img/peach.jpg',
      audioSrc: 'audio/peach.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
    {
      word: 'pear',
      translation: 'груша',
      image: 'img/pear.jpg',
      audioSrc: 'audio/pear.mp3',
      categoryId: 8,
      categoryName: 'Fruits',
    },
  ],
];

export function getCards(): Promise<ICard[][]> {
  return Promise.resolve(cards);
}

export function getCardsByCategoryId(categoryId: number): Promise<ICard[] | undefined> {
  const arrCards = cards.flat().filter((card) => card.categoryId === categoryId);
  return Promise.resolve(arrCards);
}
